self-hosted-runner:
  labels:
    - large
    - xlarge
    - two-xlarge
    - jammy

paths:
  .github/workflows/**/*.{yml,yaml}:
    ignore:
      - 'property "workflow_sha" is not defined in object type'
