# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
name: Check PR title

on:
  pull_request:
    types:
      - opened
      - edited
    branches:
      - main

jobs:
  check-pr-prefix:
    name: Check PR prefix
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check semantic version prefix
        run: python3 _check_semantic_version_prefix.py
        env:
          # Use env variable to avoid script injection
          MESSAGE: ${{ github.event.pull_request.title }}
