# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
name: Lint workflows

on:
  pull_request:

jobs:
  lint-workflows:
    name: Lint .github/workflows/
    uses: $/.github/workflows/lint_workflows.yaml
    permissions:
      contents: read
    cache-mode: none
