# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
name: Lint

on:
  pull_request:

jobs:
  actionlint:
    name: Lint workflows
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 'Foresight: Collect workflow telemetry'
        uses: runforesight/foresight-workflow-kit-action@v1
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install actionlint
        id: install
        run: |
          curl -O https://raw.githubusercontent.com/rhysd/actionlint/main/.github/actionlint-matcher.json
          echo "::add-matcher::actionlint-matcher.json"
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      - name: Run actionlint
        run: |
          "${{ steps.install.outputs.executable }}" -color
