on:
  workflow_call:
    inputs:
      track:
        description: |
          Charmhub track

          https://juju.is/docs/juju/channel#heading--track
        required: true
        type: string
      from-risk:
        description: |
          Promote from `track` input and this Charmhub risk

          https://juju.is/docs/juju/channel#heading--risk

          Must be one of "edge", "beta", "candidate"
        required: true
        type: string
      to-risk:
        description: |
          Promote to `track` input and this Charmhub risk

          https://juju.is/docs/juju/channel#heading--risk

          Must be one of "beta", "candidate", "stable"
        required: true
        type: string
      charmcraft-snap-revision:
        description: charmcraft snap revision
        required: false
        type: string
      charmcraft-snap-channel:
        description: |
          charmcraft snap channel

          Cannot be used if `charmcraft-snap-revision` input is passed
        required: false
        type: string
    secrets:
      charmhub-token:
        description: Charmhub login token
        required: true

jobs:
  promote-charms:
    name: (deprecated) Promote charms from ${{ inputs.track }}/${{ inputs.from-risk }} to ${{ inputs.track }}/${{ inputs.to-risk }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # TODO future improvement: when https://bugs.launchpad.net/snapstore-server/+bug/2097446 is
    # fixed, use isolated per-environment secrets for different risks & require manual approval to
    # access stable secret in order to improve security posture & avoid mistakes
    environment:
      name: ${{ inputs.to-risk }}
      deployment: true
    steps:
      - name: Deprecation notice
        run: |
          # shellcheck disable=SC2016
          echo '::warning::The `_promote_charms_legacy_2.yaml` workflow is deprecated & will be removed in a future release.'
      - name: Get workflow version
        id: workflow-version
        uses: canonical/get-workflow-version-action@v1
        with:
          repository-name: canonical/data-platform-workflows
          file-name: _promote_charms_legacy_2.yaml
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install CLI
        run: pipx install git+https://github.com/canonical/data-platform-workflows@"${VAR_SHA}"#subdirectory=_cli
        env:
          VAR_SHA: ${{ steps.workflow-version.outputs.sha }}
      - name: Parse charmcraft version inputs
        id: charmcraft-snap-version
        run: parse-snap-version --revision="${VAR_REVISION}" --channel="${VAR_CHANNEL}" --revision-input-name=charmcraft-snap-revision --channel-input-name=charmcraft-snap-channel
        env:
          VAR_REVISION: ${{ inputs.charmcraft-snap-revision }}
          VAR_CHANNEL: ${{ inputs.charmcraft-snap-channel }}
      - name: Install charmcraft
        run: sudo snap install charmcraft --classic ${VAR_INSTALL_FLAG:+"${VAR_INSTALL_FLAG}"}
        env:
          VAR_INSTALL_FLAG: ${{ steps.charmcraft-snap-version.outputs.install_flag }}
      - run: snap list
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0  # Checkout history with git tags
      - name: Promote charms
        id: promote
        run: promote-charms-legacy-2 --track="${VAR_TRACK}" --from-risk="${VAR_FROM_RISK}" --to-risk="${VAR_TO_RISK}" --ref="${VAR_REF}" --default-branch="${VAR_DEFAULT_BRANCH}"
        env:
          CHARMCRAFT_AUTH: ${{ secrets.charmhub-token }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VAR_TRACK: ${{ inputs.track }}
          VAR_FROM_RISK: ${{ inputs.from-risk }}
          VAR_TO_RISK: ${{ inputs.to-risk }}
          VAR_REF: ${{ github.ref }}
          VAR_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
      - name: Charmcraft logs
        if: ${{ success() || (failure() && steps.promote.outcome == 'failure') }}
        run: cat ~/.local/state/charmcraft/log/*
    permissions:
      actions: read  # Needed for GitHub API call to get workflow version (for private repositories)
      contents: write  # Needed to edit GitHub releases
