on:
  workflow_call:
    inputs:
      track:
        description: |
          Charmhub track

          https://juju.is/docs/juju/channel#heading--track
        required: true
        type: string
      from-risk:
        description:
          Promote from `track` input and this Charmhub risk

          https://juju.is/docs/juju/channel#heading--risk

          Must be one of "edge", "beta", "candidate"
        required: true
        type: string
      to-risk:
        description:
          Promote to `track` input and this Charmhub risk

          https://juju.is/docs/juju/channel#heading--risk

          Must be one of "beta", "candidate", "stable"
        required: true
        type: string
      deprecated-legacy-charms-without-charm-refresh-compatibility-version-tag:
        description: |
          (deprecated) Charm(s) do not have charm refresh compatibility version tag

          Only use this input for charms with an existing legacy track that does not have charm refresh compatibility version tags
          For new tracks, use tag_charm_edge.yaml to create the tags and do not use this input. Usage docs: https://github.com/canonical/data-platform-workflows/blob/main/.github/workflows/release_charm_edge.md
        default: false
        type: boolean
      charmcraft-snap-revision:
        description: charmcraft snap revision
        required: false
        type: string
      charmcraft-snap-channel:
        description: |
          charmcraft snap channel

          Cannot be used if `charmcraft-snap-revision` input is passed
        required: false
        type: string
    secrets:
      charmhub-token:
        description: Charmhub login token
        required: true

jobs:
  promote-charms:
    name: Promote charms from ${{ inputs.track }}/${{ inputs.from-risk }} to ${{ inputs.track }}/${{ inputs.to-risk }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # Use environment to track deployment history
    # (https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-deployments/viewing-deployment-history)
    # TODO future improvement: when https://bugs.launchpad.net/snapstore-server/+bug/2097446 is
    # fixed, use isolated per-environment secrets for different risks & require manual approval to
    # access stable secret in order to improve security posture & avoid mistakes
    environment: ${{ inputs.to-risk }}
    steps:
      - name: Get workflow version
        id: workflow-version
        uses: canonical/get-workflow-version-action@v1
        with:
          repository-name: canonical/data-platform-workflows
          file-name: _promote_charms.yaml
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install CLI
        run: pipx install git+https://github.com/canonical/data-platform-workflows@'${{ steps.workflow-version.outputs.sha }}'#subdirectory=_cli
      - name: Parse charmcraft version inputs
        id: charmcraft-snap-version
        run: parse-snap-version --revision='${{ inputs.charmcraft-snap-revision }}' --channel='${{ inputs.charmcraft-snap-channel }}' --revision-input-name=charmcraft-snap-revision --channel-input-name=charmcraft-snap-channel
      - name: Install charmcraft
        run: sudo snap install charmcraft --classic ${{ steps.charmcraft-snap-version.outputs.install_flag }}
      - run: snap list
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Checkout history with git tags
      - name: Promote charms
        id: promote
        run: promote-charms --track='${{ inputs.track }}' --from-risk='${{ inputs.from-risk }}' --to-risk='${{ inputs.to-risk }}' --ref='${{ github.ref }}' --legacy-no-refresh-compatibility-tag='${{ toJSON(inputs.deprecated-legacy-charms-without-charm-refresh-compatibility-version-tag) }}'
        env:
          CHARMCRAFT_AUTH: ${{ secrets.charmhub-token }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Charmcraft logs
        if: ${{ success() || (failure() && steps.promote.outcome == 'failure') }}
        run: cat ~/.local/state/charmcraft/log/*
