on:
  workflow_call:
    inputs:
      track:
        description: Snapcraft track
        required: true
        type: string
      from-risk:
        description: Promote from `track` input and this Snapcraft risk. Must be one of "edge", "beta", "candidate"
        required: true
        type: string
      to-risk:
        description: Promote to `track` input and this Snapcraft risk. Must be one of "beta", "candidate", "stable"
        required: true
        type: string
      snapcraft-snap-revision:
        description: Snapcraft snap revision
        required: false
        type: string
      snapcraft-snap-channel:
        description: Snapcraft snap channel. Cannot be used if `snapcraft-snap-revision` input is passed
        required: false
        type: string
      path-to-snap-directory:
        description: Relative path to snap directory from repository directory
        default: .
        type: string
    secrets:
      snap-store-token:
        description: Snap Store login token
        required: true

jobs:
  promote-snap:
    name: Promote snaps from ${{ inputs.track }}/${{ inputs.from-risk }} to ${{ inputs.track }}/${{ inputs.to-risk }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment:
      name: ${{ inputs.to-risk }}
      deployment: true
    steps:
      - name: Install CLI
        run: pipx install git+https://github.com/canonical/data-platform-workflows@"${VAR_SHA}"#subdirectory=_cli
        env:
          VAR_SHA: ${{ job.workflow_sha }}
      - name: Parse snapcraft version inputs
        id: parse-snapcraft-version
        run: parse-snap-version --revision="${VAR_REVISION}" --channel="${VAR_CHANNEL}" --revision-input-name=snapcraft-snap-revision --channel-input-name=snapcraft-snap-channel
        env:
          VAR_REVISION: ${{ inputs.snapcraft-snap-revision }}
          VAR_CHANNEL: ${{ inputs.snapcraft-snap-channel }}
      - name: Install snapcraft
        run: sudo snap install snapcraft --classic ${VAR_INSTALL_FLAG:+"${VAR_INSTALL_FLAG}"}
        env:
          VAR_INSTALL_FLAG: ${{ steps.parse-snapcraft-version.outputs.install_flag }}
      - name: List the installed snaps
        run: snap list
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 0  # Checkout history with git tags
      - name: Promote snaps
        id: promote-snaps
        run: promote-snaps --track="${VAR_TRACK}" --from-risk="${VAR_FROM_RISK}" --to-risk="${VAR_TO_RISK}" --ref="${VAR_REF}" --directory="${VAR_DIRECTORY}" --default-branch="${VAR_DEFAULT_BRANCH}"
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.snap-store-token }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VAR_TRACK: ${{ inputs.track }}
          VAR_FROM_RISK: ${{ inputs.from-risk }}
          VAR_TO_RISK: ${{ inputs.to-risk }}
          VAR_REF: ${{ github.ref }}
          VAR_DIRECTORY: ${{ inputs.path-to-snap-directory }}
          VAR_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
      - name: Snapcraft logs
        if: ${{ success() || (failure() && steps.promote-snaps.outcome == 'failure') }}
        run: cat ~/.local/state/snapcraft/log/*
    permissions:
      contents: write  # Needed to edit GitHub releases
