# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

# Usage documentation: build_charm_without_cache.md

on:
  workflow_call:
    inputs:
      artifact-name:
        description: Charm package is uploaded to this GitHub artifact name
        default: charm-packed-without-cache
        type: string
      path-to-charm-directory:
        description: Relative path to charm directory from repository directory
        default: .
        type: string
    outputs:
      artifact-name:
        description: Charm package is uploaded to this GitHub artifact name
        value: ${{ inputs.artifact-name }}

jobs:
  build:
    name: Build charm
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        run: |
          sudo adduser "$USER" lxd
          # `newgrp` does not work in GitHub Actions; use `sg` instead
          sg lxd -c "lxd waitready"
          sg lxd -c "lxd init --auto"
          # Workaround for Docker & LXD on same machine
          sudo iptables -F FORWARD
          sudo iptables -P FORWARD ACCEPT
          
          sudo snap install charmcraft --classic
          pipx install tox
          pipx install poetry
      - name: Pack charm
        id: pack
        working-directory: ${{ inputs.path-to-charm-directory }}
        run: |
          if tox list --no-desc | grep --fixed-strings --line-regexp build
          then
            sg lxd -c "tox run -e build"
          else
            sg lxd -c "charmcraft pack"
          fi
      - name: Upload charmcraft logs
        if: ${{ failure() && steps.pack.outcome == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}-charmcraft-build-logs
          path: ~/.local/state/charmcraft/log/
          if-no-files-found: error
      - name: Upload charm package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          # .empty file required to preserve directory structure
          # See https://github.com/actions/upload-artifact/issues/344#issuecomment-1379232156
          path: |
            ${{ inputs.path-to-charm-directory }}/*.charm
            .empty
          if-no-files-found: error
