# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

# Usage documentation: build_snap_without_cache.md

on:
  workflow_call:
    inputs:
      artifact-name:
        description: Snap package is uploaded to this GitHub artifact name
        default: snap-packed-without-cache
        type: string
      path-to-snap-project-directory:
        description: |
          Relative path to snap project directory from repository directory
          
          The "snap project directory" is the directory that contains the `snap` directory, not the `snap` directory itself.
        default: .
        type: string
    outputs:
      artifact-name:
        description: Snap package is uploaded to this GitHub artifact name
        value: ${{ inputs.artifact-name }}

jobs:
  build:
    name: Build snap
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        run: |
          sudo adduser "$USER" lxd
          # `newgrp` does not work in GitHub Actions; use `sg` instead
          sg lxd -c "lxd waitready"
          sg lxd -c "lxd init --auto"
          # Workaround for Docker & LXD on same machine
          sudo iptables -F FORWARD
          sudo iptables -P FORWARD ACCEPT
          
          sudo snap install snapcraft --classic
      - name: Pack snap
        id: pack
        working-directory: ${{ inputs.path-to-snap-project-directory }}
        run: sg lxd -c "snapcraft pack"
      - name: Upload snapcraft logs
        if: ${{ failure() && steps.pack.outcome == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}-snapcraft-build-logs
          path: ~/.local/state/snapcraft/log/
          if-no-files-found: error
      - name: Upload snap package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          # .empty file required to preserve directory structure
          # See https://github.com/actions/upload-artifact/issues/344#issuecomment-1379232156
          path: |
            ${{ inputs.path-to-snap-project-directory }}/*.snap
            .empty
          if-no-files-found: error
