on:
  workflow_call:

jobs:
  check-pr:
    name: Check pull request
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Install CLI
        run: pipx install git+https://github.com/canonical/data-platform-workflows@"${VAR_SHA}"#subdirectory=_cli
        env:
          VAR_SHA: ${{ job.workflow_sha }}
      - name: Check pull request
        run: check-python-package-pr-title
        # Use env variable to avoid script injection
        env:
          TITLE: ${{ github.event.pull_request.title }}
    permissions: {}
