on:
  workflow_call:

jobs:
  check-pr:
    name: Check pull request
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Get workflow version
        id: workflow-version
        uses: canonical/get-workflow-version-action@v1
        with:
          repository-name: canonical/data-platform-workflows
          file-name: check_python_package_pr.yaml
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install CLI
        run: pipx install git+https://github.com/canonical/data-platform-workflows@'${{ steps.workflow-version.outputs.sha }}'#subdirectory=_cli
      - name: Check pull request
        run: check-python-package-pr-title
        # Use env variable to avoid script injection
        env:
          TITLE: ${{ github.event.pull_request.title }}
