# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

# Usage documentation: lint_workflows.md

on:
  workflow_call:

jobs:
  lint:
    name: Lint .github/workflows/
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up environment
        run: |
          gh release --repo rhysd/actionlint download --pattern '*_linux_amd64.tar.gz' --output actionlint.tar.gz
          gh attestation verify --repo rhysd/actionlint --deny-self-hosted-runners --signer-workflow rhysd/actionlint/.github/workflows/release.yaml actionlint.tar.gz

          # Copied from https://github.com/rhysd/actionlint/blob/main/.github/actionlint-matcher.json
          cat << 'EOF' > actionlint-matcher.json
          {
            "problemMatcher": [
              {
                "owner": "actionlint",
                "pattern": [
                  {
                    "regexp": "^(?:\\x1b\\[\\d+m)?(.+?)(?:\\x1b\\[\\d+m)*:(?:\\x1b\\[\\d+m)*(\\d+)(?:\\x1b\\[\\d+m)*:(?:\\x1b\\[\\d+m)*(\\d+)(?:\\x1b\\[\\d+m)*: (?:\\x1b\\[\\d+m)*(.+?)(?:\\x1b\\[\\d+m)* \\[(.+?)\\]$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "message": 4,
                    "code": 5
                  }
                ]
              }
            ]
          }
          EOF
          echo "::add-matcher::actionlint-matcher.json"

          tar xf actionlint.tar.gz

          pipx install zizmor
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run actionlint
        run: |
          ./actionlint -color
      - name: Run zizmor
        run: zizmor .
    permissions:
      contents: read
