on:
  workflow_call:
    outputs:
      git-tag:
        description: Semantic version git tag
        value: ${{ jobs.tag.outputs.tag }}
      artifact-name:
        description: Python package distributions are uploaded to this GitHub artifact name
        value: python-package-distributions

jobs:
  tag:
    name: Tag release
    runs-on: ubuntu-latest
    concurrency:
      # Prevent race conditions
      # (If multiple commits have been pushed since the last release, this workflow may get triggered
      # on multiple commits. Without this, if the) TODO
      group: dpw-release-python-package-${{ github.ref }}
      cancel-in-progress: true
    timeout-minutes: 5
    steps:
      - name: Get workflow version
        id: workflow-version
        uses: canonical/get-workflow-version-action@v1
        with:
          repository-name: canonical/data-platform-workflows
          file-name: release_python_package_part1.yaml
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install CLI
        run: pipx install git+https://github.com/canonical/data-platform-workflows@'${{ steps.workflow-version.outputs.sha }}'#subdirectory=python/cli
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Checkout history with git tags
      - name: Determine release tag
        id: determine-tag
        run: determine-semantic-version-tag
      - name: Create tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag '${{ steps.determine-tag.outputs.tag }}' --annotate -m '${{ steps.determine-tag.outputs.tag }}'
          git push origin '${{ steps.determine-tag.outputs.tag }}'
    outputs:
      tag: ${{ steps.determine-tag.outputs.tag }}
  
  build:
    name: Build package
    needs:
      - tag
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Checkout history with git tags
      - name: Install poetry
        run: |
          pipx install poetry
          pipx inject poetry 'poetry-dynamic-versioning[plugin]'
      - name: Build package
        run: poetry build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions  # Keep in sync with `artifact-name` output
          path: dist/
