on:
  workflow_call:
    inputs:
      reviewers:
        description: Comma separated list of GitHub usernames to request to review pull request (e.g. "canonical/data-platform-engineers,octocat")
        required: false
        type: string

jobs:
  sync-docs:
    name: (deprecated) Sync docs from Discourse
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Deprecation notice
      run: |
        # shellcheck disable=SC2016
        echo '::warning::The `sync_docs.yaml` workflow is deprecated & will be removed in a future release.'
    - name: Get workflow version
      id: workflow-version
      uses: canonical/get-workflow-version-action@v1
      with:
        repository-name: canonical/data-platform-workflows
        file-name: sync_docs.yaml
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install CLI
      run: pipx install git+https://github.com/canonical/data-platform-workflows@'${{ steps.workflow-version.outputs.sha }}'#subdirectory=python/cli
    - name: Checkout
      uses: actions/checkout@v4
    - name: Update Discourse docs
      run: sync-docs
    - name: Push `sync-docs` branch & create pull request
      run: |
        git checkout -b sync-docs
        git add docs/
        # Check if changes staged
        if git diff --cached --quiet
        then
          echo 'No changes to docs/ from default git branch'
          # Delete branch on GitHub if it exists
          # (GitHub will automatically close PR if it exists)
          if git ls-remote --exit-code origin sync-docs
          then
            git push origin --delete sync-docs
          fi
          exit 0
        fi
        git config user.name "GitHub Actions"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git commit -m "Sync docs from Discourse"
        git push origin sync-docs -f
        # Create pull request
        # Capture output in variable so that step fails if `gh pr list` exits with non-zero code
        prs=$(gh pr list --head sync-docs --state open --json number)
        if [[ $prs != "[]" ]]
        then
          echo Open pull request already exists
          exit 0
        fi
        gh pr create --head sync-docs --title "Sync docs from Discourse" --body "Sync charm docs from https://discourse.charmhub.io" --label 'not bug or enhancement' --reviewer '${{ inputs.reviewers }}'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
