on:
  workflow_call:
    inputs:
      track:
        description: Charmhub track to release to
        required: true
        type: string
    outputs:
      track:
        description: Charmhub track to release to
        value: ${{ inputs.track }}

jobs:
  tag:
    name: Create charm refresh compatibility version git tag
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Install CLI
        run: pipx install git+https://github.com/canonical/data-platform-workflows@"${VAR_SHA}"#subdirectory=_cli
        env:
          VAR_SHA: ${{ job.workflow_sha }}
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: true
          fetch-depth: 0  # Checkout history with git tags
      - name: Create git tag
        run: create-charm-version-tag-edge --track="${VAR_TRACK}"
        env:
          VAR_TRACK: ${{ inputs.track }}
    permissions:
      contents: write  # Needed to create git tag
